name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: sinhluu
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            sinhluu/go-echo-http:${{github.ref_name}}-latest,
            sinhluu/go-echo-http:${{github.ref_name}}-${{ github.sha }}
